---
etcd_data_dir: /var/lib/etcd
bin_dir: /usr/local/bin
loadbalancer_apiserver_type: nginx # valid values "nginx" or "haproxy"
loadbalancer_apiserver_port: 6443
loadbalancer_apiserver_healthcheck_port: 8081
kubelet_load_modules: true
kubeadm_enabled: false
kube_read_only_port: 10255
skip_non_kubeadm_warning: true
no_proxy_exclude_workers: false
...
